CREATE TABLE ANDROIDTOKENS (
  TOKEN      VARCHAR(150) NOT NULL,
  DATEADDED  TIMESTAMP,
  /* Keys */
  PRIMARY KEY (TOKEN)
);

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES
  ON TABLE ANDROIDTOKENS
TO GONE;